/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/env.d.ts` (hash: 9a1ad0a90bac002e01e903355ff48a8b)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUDIENCE: string;
	APPROVED_EMAILS: string;
	ALLOWED_ORIGINS: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
