/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/env.d.ts` (hash: 2d395b454776603e419197fe219e76c5)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_PRODUCTION_AUDIENCE: string;
	ACCESS_PREVIEW_AUDIENCE: string;
	PRODUCTION_HOSTNAME: string;
	APPROVED_EMAILS: string;
	ALLOWED_ORIGINS: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_PRODUCTION_AUDIENCE" | "ACCESS_PREVIEW_AUDIENCE" | "PRODUCTION_HOSTNAME" | "APPROVED_EMAILS" | "ALLOWED_ORIGINS">> {}
}
